name: MeidaManageTool-Sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to GitHub
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的源仓库地址
          source-repo: "git@gitee.com:AnthonyMSen/MeidaManageTool.git"
          # 注意替换为你的目标仓库地址
          destination-repo: "git@github.com:AnthonyMSen/MeidaManageTool.git"