name: Push to Publish

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Docker
        uses: docker://alpine
        with:
          entrypoint: /bin/sh
          args: curl https://api.day.app/seHy8Styec4YKxvFBtqBte/我运行啦！

