name: Push to Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Run shell
      env:
        SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      run:
        sh $GITHUB_WORKSPACE/clean_code.sh